<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LuckyPickerWpf</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>YBH幸运摇人器</AssemblyTitle>
    <Version>26.14.0.0</Version>
    <AssemblyVersion>26.14.0.0</AssemblyVersion>
    <FileVersion>26.14.0.0</FileVersion>
    <AssemblyName>LuckyPicker</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="icon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>
</Project>
